//
//  MXMultiroomSyncLocation.h
//  MatrixSDK
//
//  Created by Artem Krachulov on 04.04.2023.
//

#import <MatrixSDK/MatrixSDK.h>

NS_ASSUME_NONNULL_BEGIN

/**
 `MXMultiroomSyncLocation` is the generic model of events received from the home server similar to `MXEvent`
 
 It contains all possible keys an event can contain. Thus, all events can be resolved
 by this model.
 */

@interface MXMultiroomSyncLocation : MXJSONModel

/**
 The event (possibly encrypted) content.
 
 @discussion
 Do not access this property directly unless you absolutely have to. Prefer to use the
 'content' property that manages decryption.
 */
@property (nonatomic) NSDictionary<NSString *, id> *wireContent;

/**
 The timestamp in ms since Epoch generated by the origin homeserver when it receives the event
 from the client.
 */
@property (nonatomic) uint64_t originServerTs;

@end

NS_ASSUME_NONNULL_END
